# Merge Arrays

In [2]:
import numpy as np

a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

c = np.r_[a,b]
c

array([1, 2, 3, 4, 5, 6, 7, 8])

In [4]:
c = np.r_[[a,b]]
c

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [6]:
c = np.c_[a,b]
c

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])